### ISSUE TITLE
Incorrect tree collapse icon offset in files navigation

### ISSUE THREAD

**Issue by yosefahab** [shaggyfeng/obsidian-Golden-Topaz-theme#9]
First off, amazing work with the colors, they're very calming, Salute!

I'm not sure if this is intended behavior or not, but the dropdown icon next to the directories seems to be offset down a little bit, which causes it to overlap with the icon underneath it.

Possible fix is to modify translateY, it should be -6 not 6 and even better add an extra .6.
```css
.nav-folder.is-collapsed .nav-folder-collapse-indicator {
    transform: translateX(-11px) translateY(-6.6px) rotate(-90deg);
    opacity: 0.4;
}
```
<img width="351" alt="Screenshot 2024-03-24 at 14 08 03" src="https://github.com/shaggyfeng/obsidian-Golden-Topaz-theme/assets/61936188/58657681-2494-48e6-a3e2-bc038fdf19ba">

- Edit: I noticed this also affects the icons in the main markdown file when using preview mode but in the opposite direction, so my fix wouldn't apply to one without affecting the other.
